// This file will be auto-generated by running: flutterfire configure
// Run this command in terminal: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This will be replaced by flutterfire configure
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for web platform yet.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3DuQXm_HFDPBLGwtxHFTCEBBcxVq0hdQ',
    appId: '1:324536405195:web:8f697d8db9a20c7f9e9f4e',
    messagingSenderId: '324536405195',
    projectId: 'heylo-56dec',
    authDomain: 'heylo-56dec.firebaseapp.com',
    storageBucket: 'heylo-56dec.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7rRH9otc_qPoJpemrjEScBkBEvgj_B3g',
    appId: '1:324536405195:android:d1785e94e0e708719e9f4e',
    messagingSenderId: '324536405195',
    projectId: 'heylo-56dec',
    storageBucket: 'heylo-56dec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEq4oTwPHQ50iddvEkkvksHLo7OwdN9us',
    appId: '1:324536405195:ios:9de24581745050709e9f4e',
    messagingSenderId: '324536405195',
    projectId: 'heylo-56dec',
    storageBucket: 'heylo-56dec.firebasestorage.app',
    iosBundleId: 'com.example.heylo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEq4oTwPHQ50iddvEkkvksHLo7OwdN9us',
    appId: '1:324536405195:ios:9de24581745050709e9f4e',
    messagingSenderId: '324536405195',
    projectId: 'heylo-56dec',
    storageBucket: 'heylo-56dec.firebasestorage.app',
    iosBundleId: 'com.example.heylo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3DuQXm_HFDPBLGwtxHFTCEBBcxVq0hdQ',
    appId: '1:324536405195:web:60b878dccf7db2ad9e9f4e',
    messagingSenderId: '324536405195',
    projectId: 'heylo-56dec',
    authDomain: 'heylo-56dec.firebaseapp.com',
    storageBucket: 'heylo-56dec.firebasestorage.app',
  );

}